### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by migueldelmazo** [Adalab/evaluacion-intermedia-modulo-2-ibelreal#1]
Really cool job @ibelreal  !!!

Here you have some tips to improve the exercise:

### JavaScript: basic

- [x] You are writing many times "trackEl.innerHTML = 'something';", what about making a function that accepts a string as param and paints it into 'trackEl'?
- [x] Remember that every time we use `.innerHTML` or `.value` to get DOM content we receive a string. Sometimes we will need to use something like `parseInt()` to convert it to a number.

### HTML

- [x] Use placeholder.

**Comment by migueldelmazo** [comment]
@ibelreal muy muy muy buen ejercicio, se nota que lo entiendes y que eres capaz de ir más allá de mis explicaciones y de la clase. 

Puedes estar muy orgullosa!!!

**Comment by ibelreal** [comment]
Gracias @migueldelmazo
